# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cc1111usbgui.ui'
#
# Created: Mon Nov 21 21:04:03 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 635)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerWidget = QtGui.QWidget(self.centralwidget)
        self.registerWidget.setObjectName("registerWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.registerWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.registerLabel = QtGui.QLabel(self.registerWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.registerLabel.setFont(font)
        self.registerLabel.setObjectName("registerLabel")
        self.verticalLayout.addWidget(self.registerLabel)
        self.registerTable = QtGui.QTableWidget(self.registerWidget)
        self.registerTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.registerTable.setObjectName("registerTable")
        self.registerTable.setColumnCount(2)
        self.registerTable.setRowCount(39)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(31, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(32, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(33, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(34, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(35, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(36, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(37, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(38, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(13, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(14, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(14, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(15, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(15, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(16, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(16, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(17, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(17, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(18, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(18, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(19, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(19, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(20, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(20, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(21, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(21, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(22, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(22, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(23, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(23, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(24, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(24, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(25, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(25, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(26, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(26, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(27, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(27, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(28, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(28, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(29, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(29, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(30, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(30, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(31, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(31, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(32, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(32, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(33, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(33, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(34, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(34, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(35, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(35, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(36, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(36, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(37, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(37, 1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(38, 0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setItem(38, 1, item)
        self.registerTable.horizontalHeader().setVisible(True)
        self.registerTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.registerTable)
        self.horizontalLayout.addWidget(self.registerWidget)
        self.contentWidget = QtGui.QWidget(self.centralwidget)
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.contentWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.functionsTab = QtGui.QTabWidget(self.contentWidget)
        self.functionsTab.setEnabled(True)
        self.functionsTab.setObjectName("functionsTab")
        self.transmitTab = QtGui.QWidget()
        self.transmitTab.setObjectName("transmitTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.transmitTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.parameterSendBox = QtGui.QGroupBox(self.transmitTab)
        self.parameterSendBox.setObjectName("parameterSendBox")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.parameterSendBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sendcountLabel = QtGui.QLabel(self.parameterSendBox)
        self.sendcountLabel.setObjectName("sendcountLabel")
        self.horizontalLayout_5.addWidget(self.sendcountLabel)
        self.countSendBox = QtGui.QSpinBox(self.parameterSendBox)
        self.countSendBox.setMinimum(1)
        self.countSendBox.setObjectName("countSendBox")
        self.horizontalLayout_5.addWidget(self.countSendBox)
        self.continiousSendBox = QtGui.QCheckBox(self.parameterSendBox)
        self.continiousSendBox.setObjectName("continiousSendBox")
        self.horizontalLayout_5.addWidget(self.continiousSendBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.startSendButton = QtGui.QPushButton(self.parameterSendBox)
        self.startSendButton.setObjectName("startSendButton")
        self.horizontalLayout_5.addWidget(self.startSendButton)
        self.stopSendButton = QtGui.QPushButton(self.parameterSendBox)
        self.stopSendButton.setEnabled(False)
        self.stopSendButton.setObjectName("stopSendButton")
        self.horizontalLayout_5.addWidget(self.stopSendButton)
        self.verticalLayout_4.addWidget(self.parameterSendBox)
        self.widget_2 = QtGui.QWidget(self.transmitTab)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_3 = QtGui.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtGui.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtGui.QRadioButton(self.widget_3)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.widget_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.widget_3)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.widget_3)
        self.groupBox_2 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 4)
        self.functionsTab.addTab(self.transmitTab, "")
        self.receiveTab = QtGui.QWidget()
        self.receiveTab.setObjectName("receiveTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.receiveTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.parameterRecvBox = QtGui.QGroupBox(self.receiveTab)
        self.parameterRecvBox.setObjectName("parameterRecvBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.parameterRecvBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.receiveLabel = QtGui.QLabel(self.parameterRecvBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveLabel.sizePolicy().hasHeightForWidth())
        self.receiveLabel.setSizePolicy(sizePolicy)
        self.receiveLabel.setObjectName("receiveLabel")
        self.horizontalLayout_3.addWidget(self.receiveLabel)
        self.countRecvBox = QtGui.QSpinBox(self.parameterRecvBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countRecvBox.sizePolicy().hasHeightForWidth())
        self.countRecvBox.setSizePolicy(sizePolicy)
        self.countRecvBox.setMinimum(1)
        self.countRecvBox.setObjectName("countRecvBox")
        self.horizontalLayout_3.addWidget(self.countRecvBox)
        self.continiousRecvBox = QtGui.QCheckBox(self.parameterRecvBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continiousRecvBox.sizePolicy().hasHeightForWidth())
        self.continiousRecvBox.setSizePolicy(sizePolicy)
        self.continiousRecvBox.setObjectName("continiousRecvBox")
        self.horizontalLayout_3.addWidget(self.continiousRecvBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.startRecvButton = QtGui.QPushButton(self.parameterRecvBox)
        self.startRecvButton.setObjectName("startRecvButton")
        self.horizontalLayout_3.addWidget(self.startRecvButton)
        self.stopRecvButton = QtGui.QPushButton(self.parameterRecvBox)
        self.stopRecvButton.setEnabled(False)
        self.stopRecvButton.setObjectName("stopRecvButton")
        self.horizontalLayout_3.addWidget(self.stopRecvButton)
        self.verticalLayout_3.addWidget(self.parameterRecvBox)
        self.widget = QtGui.QWidget(self.receiveTab)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.receiveTable = QtGui.QTableWidget(self.widget)
        self.receiveTable.setObjectName("receiveTable")
        self.receiveTable.setColumnCount(3)
        self.receiveTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.receiveTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.receiveTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.receiveTable.setHorizontalHeaderItem(2, item)
        self.receiveTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.receiveTable)
        self.statusBox = QtGui.QGroupBox(self.widget)
        self.statusBox.setObjectName("statusBox")
        self.horizontalLayout_2.addWidget(self.statusBox)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.functionsTab.addTab(self.receiveTab, "")
        self.detectionTab = QtGui.QWidget()
        self.detectionTab.setEnabled(True)
        self.detectionTab.setObjectName("detectionTab")
        self.label_2 = QtGui.QLabel(self.detectionTab)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 59, 16))
        self.label_2.setObjectName("label_2")
        self.functionsTab.addTab(self.detectionTab, "")
        self.snifferTab = QtGui.QWidget()
        self.snifferTab.setEnabled(True)
        self.snifferTab.setObjectName("snifferTab")
        self.label_3 = QtGui.QLabel(self.snifferTab)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 59, 16))
        self.label_3.setObjectName("label_3")
        self.functionsTab.addTab(self.snifferTab, "")
        self.relayTab = QtGui.QWidget()
        self.relayTab.setEnabled(True)
        self.relayTab.setObjectName("relayTab")
        self.label_4 = QtGui.QLabel(self.relayTab)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 59, 16))
        self.label_4.setObjectName("label_4")
        self.functionsTab.addTab(self.relayTab, "")
        self.jammingTab = QtGui.QWidget()
        self.jammingTab.setEnabled(True)
        self.jammingTab.setObjectName("jammingTab")
        self.label_5 = QtGui.QLabel(self.jammingTab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 59, 16))
        self.label_5.setObjectName("label_5")
        self.functionsTab.addTab(self.jammingTab, "")
        self.verticalLayout_2.addWidget(self.functionsTab)
        self.registerGroup = QtGui.QGroupBox(self.contentWidget)
        self.registerGroup.setObjectName("registerGroup")
        self.verticalLayout_2.addWidget(self.registerGroup)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.contentWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDongle = QtGui.QMenu(self.menubar)
        self.menuDongle.setObjectName("menuDongle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionStatus = QtGui.QAction(MainWindow)
        self.actionStatus.setObjectName("actionStatus")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuDongle.addAction(self.actionConnect)
        self.menuDongle.addAction(self.actionStatus)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDongle.menuAction())

        self.retranslateUi(MainWindow)
        self.functionsTab.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CC1111USB Client", None, QtGui.QApplication.UnicodeUTF8))
        self.registerLabel.setText(QtGui.QApplication.translate("MainWindow", "Registers", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(10).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(11).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(12).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(13).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(14).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(15).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(16).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(17).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(18).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(19).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(20).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(21).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(22).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(23).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(24).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(25).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(26).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(27).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(28).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(29).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(30).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(31).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(32).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(33).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(34).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(35).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(36).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(37).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.verticalHeaderItem(38).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Reg.", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Val.", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.registerTable.isSortingEnabled()
        self.registerTable.setSortingEnabled(False)
        self.registerTable.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "IOCFG2", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "0x00", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "IOCFG1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "0x00", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "IOCFG0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(2, 1).setText(QtGui.QApplication.translate("MainWindow", "0x06", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(3, 0).setText(QtGui.QApplication.translate("MainWindow", "SYNC1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(3, 1).setText(QtGui.QApplication.translate("MainWindow", "0xD3", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(4, 0).setText(QtGui.QApplication.translate("MainWindow", "SYNC0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(4, 1).setText(QtGui.QApplication.translate("MainWindow", "0x91", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(5, 0).setText(QtGui.QApplication.translate("MainWindow", "PKTLEN", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(5, 1).setText(QtGui.QApplication.translate("MainWindow", "0xFF", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(6, 0).setText(QtGui.QApplication.translate("MainWindow", "PKTCTRL1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(6, 1).setText(QtGui.QApplication.translate("MainWindow", "0x00", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(7, 0).setText(QtGui.QApplication.translate("MainWindow", "PKTCTRL0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(7, 1).setText(QtGui.QApplication.translate("MainWindow", "0x05", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(8, 0).setText(QtGui.QApplication.translate("MainWindow", "ADDR", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(8, 1).setText(QtGui.QApplication.translate("MainWindow", "0x00", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(9, 0).setText(QtGui.QApplication.translate("MainWindow", "CHANNR", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(9, 1).setText(QtGui.QApplication.translate("MainWindow", "0x00", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(10, 0).setText(QtGui.QApplication.translate("MainWindow", "FSCTRL1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(10, 1).setText(QtGui.QApplication.translate("MainWindow", "0x08", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(11, 0).setText(QtGui.QApplication.translate("MainWindow", "FSCTRL0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(11, 1).setText(QtGui.QApplication.translate("MainWindow", "0x00", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(12, 0).setText(QtGui.QApplication.translate("MainWindow", "FREQ2", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(12, 1).setText(QtGui.QApplication.translate("MainWindow", "0x24", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(13, 0).setText(QtGui.QApplication.translate("MainWindow", "FREQ1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(13, 1).setText(QtGui.QApplication.translate("MainWindow", "0x2D", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(14, 0).setText(QtGui.QApplication.translate("MainWindow", "FREQ0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(14, 1).setText(QtGui.QApplication.translate("MainWindow", "0xDD", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(15, 0).setText(QtGui.QApplication.translate("MainWindow", "MDMCFG4", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(15, 1).setText(QtGui.QApplication.translate("MainWindow", "0xCA", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(16, 0).setText(QtGui.QApplication.translate("MainWindow", "MDMCFG3", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(16, 1).setText(QtGui.QApplication.translate("MainWindow", "0xA3", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(17, 0).setText(QtGui.QApplication.translate("MainWindow", "MDMCFG2", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(17, 1).setText(QtGui.QApplication.translate("MainWindow", "0x93", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(18, 0).setText(QtGui.QApplication.translate("MainWindow", "MDMCFG1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(18, 1).setText(QtGui.QApplication.translate("MainWindow", "0x23", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(19, 0).setText(QtGui.QApplication.translate("MainWindow", "MDMCFG0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(19, 1).setText(QtGui.QApplication.translate("MainWindow", "0x11", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(20, 0).setText(QtGui.QApplication.translate("MainWindow", "DEVIATN", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(20, 1).setText(QtGui.QApplication.translate("MainWindow", "0x36", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(21, 0).setText(QtGui.QApplication.translate("MainWindow", "MCSM2", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(21, 1).setText(QtGui.QApplication.translate("MainWindow", "0x07", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(22, 0).setText(QtGui.QApplication.translate("MainWindow", "MCSM1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(22, 1).setText(QtGui.QApplication.translate("MainWindow", "0x30", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(23, 0).setText(QtGui.QApplication.translate("MainWindow", "MCSM0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(23, 1).setText(QtGui.QApplication.translate("MainWindow", "0x18", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(24, 0).setText(QtGui.QApplication.translate("MainWindow", "FOCCFG", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(24, 1).setText(QtGui.QApplication.translate("MainWindow", "0x16", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(25, 0).setText(QtGui.QApplication.translate("MainWindow", "BSCFG", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(25, 1).setText(QtGui.QApplication.translate("MainWindow", "0x6C", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(26, 0).setText(QtGui.QApplication.translate("MainWindow", "AGCCTRL2", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(26, 1).setText(QtGui.QApplication.translate("MainWindow", "0x43", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(27, 0).setText(QtGui.QApplication.translate("MainWindow", "AGCCTRL1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(27, 1).setText(QtGui.QApplication.translate("MainWindow", "0x40", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(28, 0).setText(QtGui.QApplication.translate("MainWindow", "AGCCTRL0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(28, 1).setText(QtGui.QApplication.translate("MainWindow", "0x91", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(29, 0).setText(QtGui.QApplication.translate("MainWindow", "FREND1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(29, 1).setText(QtGui.QApplication.translate("MainWindow", "0x56", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(30, 0).setText(QtGui.QApplication.translate("MainWindow", "FREND0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(30, 1).setText(QtGui.QApplication.translate("MainWindow", "0x10", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(31, 0).setText(QtGui.QApplication.translate("MainWindow", "FSCAL3", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(31, 1).setText(QtGui.QApplication.translate("MainWindow", "0xE9", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(32, 0).setText(QtGui.QApplication.translate("MainWindow", "FCSAL2", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(32, 1).setText(QtGui.QApplication.translate("MainWindow", "0x2A", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(33, 0).setText(QtGui.QApplication.translate("MainWindow", "FSCAL1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(33, 1).setText(QtGui.QApplication.translate("MainWindow", "0x00", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(34, 0).setText(QtGui.QApplication.translate("MainWindow", "FSCAL0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(34, 1).setText(QtGui.QApplication.translate("MainWindow", "0x1F", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(35, 0).setText(QtGui.QApplication.translate("MainWindow", "TEST2", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(35, 1).setText(QtGui.QApplication.translate("MainWindow", "0x88", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(36, 0).setText(QtGui.QApplication.translate("MainWindow", "TEST1", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(36, 1).setText(QtGui.QApplication.translate("MainWindow", "0x31", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(37, 0).setText(QtGui.QApplication.translate("MainWindow", "TEST0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(37, 1).setText(QtGui.QApplication.translate("MainWindow", "0x09", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(38, 0).setText(QtGui.QApplication.translate("MainWindow", "PA_TABLE0", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.item(38, 1).setText(QtGui.QApplication.translate("MainWindow", "0x50", None, QtGui.QApplication.UnicodeUTF8))
        self.registerTable.setSortingEnabled(__sortingEnabled)
        self.parameterSendBox.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.sendcountLabel.setText(QtGui.QApplication.translate("MainWindow", "Send count", None, QtGui.QApplication.UnicodeUTF8))
        self.continiousSendBox.setText(QtGui.QApplication.translate("MainWindow", "Continious", None, QtGui.QApplication.UnicodeUTF8))
        self.startSendButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopSendButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Plain text", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Hexadecimal", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.functionsTab.setTabText(self.functionsTab.indexOf(self.transmitTab), QtGui.QApplication.translate("MainWindow", "Transmit", None, QtGui.QApplication.UnicodeUTF8))
        self.parameterRecvBox.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.receiveLabel.setText(QtGui.QApplication.translate("MainWindow", "Receive count", None, QtGui.QApplication.UnicodeUTF8))
        self.continiousRecvBox.setText(QtGui.QApplication.translate("MainWindow", "Continious", None, QtGui.QApplication.UnicodeUTF8))
        self.startRecvButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopRecvButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.receiveTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.receiveTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.receiveTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.statusBox.setTitle(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.functionsTab.setTabText(self.functionsTab.indexOf(self.receiveTab), QtGui.QApplication.translate("MainWindow", "Receive", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TBD", None, QtGui.QApplication.UnicodeUTF8))
        self.functionsTab.setTabText(self.functionsTab.indexOf(self.detectionTab), QtGui.QApplication.translate("MainWindow", "Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "TBD", None, QtGui.QApplication.UnicodeUTF8))
        self.functionsTab.setTabText(self.functionsTab.indexOf(self.snifferTab), QtGui.QApplication.translate("MainWindow", "Sniffer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "TBD", None, QtGui.QApplication.UnicodeUTF8))
        self.functionsTab.setTabText(self.functionsTab.indexOf(self.relayTab), QtGui.QApplication.translate("MainWindow", "Relay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "TBD", None, QtGui.QApplication.UnicodeUTF8))
        self.functionsTab.setTabText(self.functionsTab.indexOf(self.jammingTab), QtGui.QApplication.translate("MainWindow", "Jamming", None, QtGui.QApplication.UnicodeUTF8))
        self.registerGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Register description", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDongle.setTitle(QtGui.QApplication.translate("MainWindow", "Dongle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatus.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))

