

#define FHSS_STATE_UNSYNCHED    0
#define FHSS_STATE_DISCOVERY    1
#define FHSS_STATE_SYNCHING     2
#define FHSS_STATE_SYNCHED      3
#define FHSS_STATE_SYNC_MASTER  4
#define FHSS_STATE_SYNCINGMASTER 5

